config/routes.rb
Worldmap::Application.routes.draw do
  
 

     
     
 resources :colleagues do

    collection do
      get "map"
      get "search"
      get "list"
      get "searchinloc"
      get "allpins"
      get "autocomplete"
   get "locationlist"
    end

 end

 root :to => redirect("/worldmap/colleagues/map")

end

app/models/colleague.rb
class Colleague < ActiveRecord::Base
  attr_accessible :location, :name, :project, :latitude, :longitude, :longlat

  attr_accessible :email, :role, :contactnum

  attr_accessible :attachment


  attr_accessor :attachment,:longlat

has_attached_file :attachment, :default_url => "../../../missing-small.png",:styles => {
    :thumb=> "100x100#",
    :small  => "150x150>",
    :medium => "300x300>",
    :large =>   "400x400>" }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/colleagues_controller.rb
class ColleaguesController < ApplicationController
  # GET /colleagues
  # GET /colleagues.json
  def index

    @colleagues= Colleague.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @colleagues }
    end

  end

  # GET /colleagues/1
  # GET /colleagues/1.json
  def show
    @colleague = Colleague.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @colleague }
    end
  end

  # GET /colleagues/new
  # GET /colleagues/new.json
  def new
    @colleague = Colleague.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @colleague }
    end
  end

  # GET /colleagues/1/edit
  def edit
    @colleague = Colleague.find(params[:id])
  end

  # POST /colleagues
  # POST /colleagues.json

  def create
    @colleague = Colleague.new(params[:colleague])
    

    respond_to do |format|
        if @colleague.save 

          flash[:notice] = "Colleague was successfully created."
          format.html { redirect_to @colleague}
          format.json { render json: @colleague, status: :created, location: @colleague }
        else
         flash[:notice] = 'Invalid location!'
         format.html { redirect_to new_colleague_path, notice: 'Invalid location.'}
         format.json { render json: @colleague.errors, status: :unprocessable_entity }
       end
    end
end

  # PUT /colleagues/1
  # PUT /colleagues/1.json
  def update
    @colleague = Colleague.find(params[:id])

    respond_to do |format|
      if @colleague.update_attributes(params[:colleague])
        flash[:notice] = "Colleague was successfully Updated."
        format.html { redirect_to @colleague}
        format.json { head :no_content }
      else
        flash[:notice] = "Colleague was Not Updated."
        format.html { render action: "edit" }
        format.json { render json: @colleague.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colleagues/1
  # DELETE /colleagues/1.json
  def destroy
    @colleague = Colleague.find(params[:id])
    @colleague.destroy

    respond_to do |format|
      format.html { redirect_to colleagues_url }
      format.json { head :no_content }
    end
  end


  def autocomplete

    #p "inside autocomplete"

    @colleagues=Colleague.all
    @list="["
    @name='"name":'

    @start="{"
    @end="}"
    @colleagues.each do |colleague|

      @list= @list+ @start+ 
      @name + '"'+colleague.name+'"'+
      @end+","


    end
    @list = @list[0..@list.length-2]
    @list = @list +"]"

    render :inline =>@list


  end

  def list
    #p "$$$$$$$$$$$$$$$$$$$$$$$"


    #p params[:test]
    @colleagues1=Colleague.where(:location=>  params[:test])

  end
  def locationlist
    loc=params[:loc]



    @collegues= @users=Colleague.where(:location=>loc)
    #p @colleagues


    @location="["
    @place='"cname":'
    @image='"image":'
    @project='"project":'
    @start="{"
    @end="}"
    @collegues.each do |colleague|


      if colleague.attachment.blank?

        # p "^^^^^^^^^^^^^^^^&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&"
        # p "inside if of controller"

        # p "^^^^^^^^^^^^^^^^"


        @location= @location+ @start+ 
        @place + '"'+colleague.name+'",'+
        @project + '"'+colleague.project+'",'+
        @image+'"'+'../assets/missing-small.png'+'"' +

        @end+","

      else

        @location= @location+ @start+ 
        @place + '"'+colleague.name+'",'+
        @project + '"'+colleague.project+'",'+
        @image+'"..'+colleague.attachment.url(:small)+'"' +

        @end+","

      end





    end
    @location = @location[0..@location.length-2]
    @location = @location +"]"
    # p "^^^^^^^^^^^^^^^^"
    # p @location

    render :inline =>@location

  end

  def search
    name=params[:search]



    @collegues= @users=Colleague.where(:name=>name)
    @location="["
    @place='"place":'
    @image='"image":'
    @start="{"
    @end="}"
    @collegues.each do |colleague|

      if colleague.attachment.blank?

        # p "^^^^^^^^^^^^^^^^&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&"
        # p "inside if of controller"

        # p "^^^^^^^^^^^^^^^^"


        @location= @location+ @start+ 
        @place + '"'+colleague.location+'",'+
        @image+'"'+'../assets/missing-small.png'+'"' +

        @end+","

      else

        @location= @location+ @start+ 
        @place + '"'+colleague.location+'",'+
        @image+'"..'+colleague.attachment.url(:small)+'"' +

        @end+","

      end


    end
    @location = @location[0..@location.length-2]
    @location = @location +"]"
    # p "^^^^^^^^^^^^^^^^"
    # p @location

    render :inline =>@location
  end




  def searchinloc
    name=params[:search]
    loc=params[:loc]
    @users=Colleague.where(:name=>name,:location=>loc)
    @users.each do |user| 
      @name=user.name
      @location=user.location
      render :inline=>"" 
    end
  end

  def allpins

    # p "inside allpinssss"
    @collegues=Colleague.select("DISTINCT location,longitude,latitude")
    @location="["
    @place='"place":'
    @longitude='"longitude":'
    @latitude='"latitude":'
    @countno='"count":'
    @start="{"
    @end="}"
    @collegues.each do |colleague|
      @count=  Colleague.where(:location=> colleague.location).count 
      @location= @location+ @start+ 
      @place + '"'+colleague.location+'",'+
      @longitude+'"'+colleague.longitude+'",' +
      @latitude+'"'+colleague.latitude+'",'+
      @countno+'"'+ @count.to_s+'"'+
      @end+","


    end
    @location = @location[0..@location.length-2]
    @location = @location +"]"
    # p "^^^^^^^^^^^^^^^^"
    # p @location

    render :inline =>@location
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colleagues_helper.rb
module ColleaguesHelper
end

app/views/colleagues/_form.html.erb
<!DOCTYPE html>

<head>
 <meta charset="utf-8" />
 <script
src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDY0kkJiTPVd2U7aTOAwhc9ySH6oHxOIYM&sensor=false">
 </script>
 <script>

 function latlong()
 { 
 var address = document.getElementById("address").value;
 var geocoder = new google.maps.Geocoder();

 geocoder.geocode( { 'address': address}, function(results, status) {
  if (results=="")
   { alert("Location you entered was not found");
   document.getElementById("address").focus();}
  else
  var location = results[0].geometry.location;

  document.getElementById("latitude").value=location.lat();
  document.getElementById("longitude").value=location.lng();
});
}
</script>
</head>




<%= form_for(@colleague, :html => {:multipart => true}) do |f| %>
<% if @colleague.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@colleague.errors.count, "error") %> prohibited this colleague from being saved:</h2>

  <ul>
    <% @colleague.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>



<table>
  <tr>
    <td><font size="3px">Name : </font></td>
    <td> <%= f.text_field :name , :required => true %></td>
  </tr>

  <tr>
    <td><font size="3px">Role : </font></td>
    <td> <%= f.text_field :role , :required => true %></td>
  </tr>

  <tr>
    <td> <font size="3px">Location : </font></td>
    <td> <%= f.text_field :location, :required => true,:id=>"address", :onChange =>
    "latlong();" %></td>
  </tr>
  <tr>
    <td> <font size="3px">Project : </font></td>
    <td> <%= f.text_field :project , :required => true %></td>
  </tr>

  <tr>
    <td><font size="3px">Contact Number :</td>
    <td> <%= f.text_field :contactnum %></td>
  </tr>

  <tr>
    <td><font size="3px">Email ID :</td>
    <td> <%= f.text_field :email %></td>
  </tr>

  <tr>
    <td><font size="3px">Attach Picture :</td>
    <td> <%= f.file_field :attachment %></td>
  </tr>
   <tr>
    <td> <%= f.hidden_field :latitude ,:id=>"latitude", :required => true ,:readonly => true%></td>
    <td> <%= f.hidden_field :longitude ,:id=>"longitude", :required => true ,:readonly => true%></td>
  </tr>
</table>
<br/>
<%= f.submit "Save", :class=> 'btn btn-primary' %>

<%= link_to 'Back', colleagues_path, :class=> 'btn' %>

<br/>
<br/>
</div>

<% end %>

<br/>
<br/>
<br/>

app/views/colleagues/edit.html.erb
<div style="display: inline-block; margin-right:800px">
  <%= link_to image_tag("icon_map.png"), map_colleagues_path , title: 'AppDev Map', rel: 'tooltip' %>
  <%= link_to image_tag("icon_list.png"), colleagues_path , title: 'Colleagues List', rel: 'tooltip' %>
  
</div>


<div class="hr"></div>
</div><h2>Edit colleague</h2>

<%= render 'form' %>

<br/>
<br/>
<br/>

app/views/colleagues/index.html.erb
<div style="display: inline-block; margin-right:800px">
  <%= link_to image_tag("icon_map.png"), map_colleagues_path , title: 'AppDev Map', rel: 'tooltip' %>
  <%= link_to image_tag("icon_list_selected.png"), colleagues_path , title: 'Colleagues List', rel: 'tooltip' %>
  
</div>




<div class="hr"></div>
</div>


<table border="0" class="index_table" id="index_table" style="display: none width:800px;">
 <thead>
   <tr>
     <th></th>
     <th></th>
     <th></th>
     <th></th>
     <th></th>
   </tr>
 </thead>
 <tbody>
   <% @colleagues.each do |colleague| %>
  
      <% if colleague.attachment.blank? %>
      <td style="width:200px" > <%= image_tag ("missing-small.png")></td>
      <% else %>
      <td style="width:200px" > <%= image_tag colleague.attachment.url(:small) %></td>
      <% end %>

      <td style="width: 250px"><b>
        <FONT COLOR=ORANGE SIZE=4>
          <%= colleague.name %></b></FONT><br/>
          <%= colleague.role %><br/>
          <%= colleague.project %><br/>


          

        </td>


        <td style="width:250px">
          <br/><br/>
          <b>Office Location : </b><%= colleague.location %><br/>


          <% if colleague.email.blank? %>
          <b>E-mail : </b>Not Available<br/>
          <% else %>
          <b>E-mail : </b><%= colleague.email %><br/>
          <% end %>

          <% if colleague.contactnum.blank? %>
          <b>Contact Number : </b>Not Available<br/>
          <% else %>
          <b>Contact Number : </b><%= colleague.contactnum %><br/>
          <% end %>


        </td>

        <td width="50px"><b><%= link_to(image_tag("edit2.png", :border => 0) , edit_colleague_path(colleague) )%></b></td>
        <td width="50px"><b><%= link_to(image_tag("remove2.png", :border => 0), colleague, confirm: 'Are you sure?', method: :delete )%></b></td>
      </tr>
     
      <% end %>



    </tbody>
  </table>
  <br />
  <%= link_to(image_tag("add2.png", :border => 0) , new_colleague_path )%>
  <br/>
  <br/>
  <br/>
</div>
<br/>
<br/>
</div>
<br/>
<br/>
<br/>

app/views/colleagues/list.html.erb
<div style="display: inline-block; margin-right:800px">
  <%= link_to image_tag("icon_map.png"), map_colleagues_path , title: 'AppDev Map', rel: 'tooltip' %>
  <%= link_to image_tag("icon_list.png"), colleagues_path , title: 'Colleagues List', rel: 'tooltip' %>
  
</div>


<div class="hr"></div>
</div>
<div class="userlist">
  <h2>Colleagues in <%="#{params[:loc]}"%></h2>

</div>



<div class="list_content">
     <%= paginate @colleagues %>
<table border="0">
     <thead> 
     
     </thead>
      <tbody>
     <% @colleagues.each do |colleague| %>
     <tr >


       <tr>
        <%  if colleague.attachment.blank? %>
          <td style="width:200px" >  <%= image_tag ("missing-small.png") %></td>
        <% else %>
          <td style="width:200px" >  <%= image_tag colleague.attachment.url(:small) %></td>
        <% end %>
        
        <td style=" padding-right: 5px; padding-left: 5px; width: 200px"><b>
          <FONT COLOR=ORANGE SIZE=4>
          <%= colleague.name %></b></FONT><br/>
          <%= colleague.role %><br/>
          <%= colleague.project %><br/>


          

        </td>


        <td style="min-width:100px">
          <br/><br/>
          <b>Office Location : </b><%= colleague.location %><br/>


          <%  if colleague.email.blank? %>
            <b>E-mail : </b>Not Available<br/>
          <% else %>
            <b>E-mail : </b><%= colleague.email %><br/>
          <% end %>

          <%  if colleague.contactnum.blank? %>
            <b>Contact Number : </b>Not Available<br/>
          <% else %>
            <b>Contact Number : </b><%= colleague.contactnum %><br/>
          <% end %>


       </td>

       <td width="5%"><b><%= link_to(image_tag("edit2.png", :border => 0) , edit_colleague_path(colleague) )%></b></td>
       <td width="5%"><b><%= link_to(image_tag("remove2.png", :border => 0), colleague, confirm: 'Are you sure?', method: :delete )%></b></td>
     </tr>
     <tr><td colspan="6"><div class="table_hr"></div>
     </td></tr>
     <% end %>



   </tbody>
    </table>
    <br />

<br/>
<br/>
<br/>
</div>
<br/>
<br/>
</div>
<br/>
<br/>
<br/>

<script type="text/javascript">
function searchUserinLocation(location)
{
  alert(location);
   name=document.getElementById("name").value;
    
     $.ajax({
    url: '/colleagues/searchinloc?search='+name+'&loc='+location,
    error: function (XMLHttpRequest, textStatus, errorThrown) {
      alert("Something went wrong!! Please try again later.");
                
    },
    success: function(data){
        jQuery("#userlist").html(data);
    },
    type: "get"
  });  
 }
}
</script>

app/views/colleagues/map.html.erb
<div class="container">
<div id="example" class="modal hide fade in" style="display: none; width:700px ;height:500px; ">

    <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>List of colleagues</h3>
    </div>
    <div class="modal-body">
    <p>
<div id="test">

    </p>
</div>
</div>
</div>
</div>

<div style="display: inline-block; margin-right:800px">
  <%= link_to image_tag("icon_map_selected.png"), map_colleagues_path , title: 'AppDev Map', rel: 'tooltip' %>
  <%= link_to image_tag("icon_list.png"), colleagues_path , title: 'Colleagues List', rel: 'tooltip' %>
  
</div>





<div class="hr"></div>
<div style="float:right; display:inline-block; margin-top:10px">

  <input  id="name" type="text" size="40" value="Enter Colleague Name" onfocus="if(this.value=='Enter Colleague Name')this.value=''" onblur="if(this.value=='')this.value='Enter Colleague Name'" onKeydown="Javascript: if (event.keyCode==13) center();" />
  <!-- <input style="display:inline-block vertical-align:middle" type="button" value="Search" onclick="center()" class="btn  btn-custom" >
 -->

</div>

<!DOCTYPE html>
<html>
<head>
 <meta charset="utf-8" />
 <script
 src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDY0kkJiTPVd2U7aTOAwhc9ySH6oHxOIYM&sensor=false">
 </script>

 <style type="text/css">
 img[src*="iws3.png"] {
  display: none;
}
</style>


<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css" />

<input type="hidden" value="" id="location"/> 
<script>

function loadlist(location)
{

 var popuplist=[];
  var list;
    $.ajax({
      url: '../colleagues/locationlist?loc='+location,
      error: function (XMLHttpRequest, textStatus, errorThrown) {
        alert("Something went wrong!! Please try again later.");

      },
      success: function(data){

    
          var jsonObj = $.parseJSON(data);

    $('#test').append(' <table border="0" id="display" class="paginated" style="width:600px min-height:700px"><thead><tr><th scope="col" style="width:200px"></th><th scope="col"style="width:200px">Name</th><th scope="col" style="width:200px">Project</th></tr></thead><tbody>');

            $.each(jsonObj,function(key,val){
 list=list+'<tr><td>'+'<img src='+val.image+'></td><td>'+val.cname+'</td><td>'+val.project+'</td>'+'</tr>';
  

  });
      
  

        $('#display tbody').append(list+'</tbody></table>');


$('#display').dataTable();

      
    name="";
    image="";
     },
     type: "get"
   });  
$("#display tr").remove();
$("#display thead").remove();
$("#test").empty();
}
$(document).ready(function() {
  var availableTags=[];
  var NoResultsLabel = "No Results";
        $.ajax({
          url: '../colleagues/autocomplete',
          error: function (XMLHttpRequest,textStatus,errorThrown) {
          alert("Something went wrong!! Please try again later. Unable to load colleagues list");

      },
      success: function(data){
      jQuery("#search_user").html("This Person is based in " +data);
      var jsonObj = $.parseJSON(data);
      $.each(jsonObj,function(index,value){
      availableTags.push(value.name);
   

  });


    },
    type: "get"
  });  
$( "#name" ).autocomplete({
  
  source: function( request, response ) {
    var matches = $.map( availableTags, function(tag) {
      if ( tag.toUpperCase().indexOf(request.term.toUpperCase()) === 0 ) {
        return tag;
      }
    });
     if (!matches.length) {
                matches = [NoResultsLabel];
            }
    response(matches);

  },
    select: function (a,b) {
      $(this).val(b.item.value);
     center();
    }
});

//$( "#name" ).autocomplete({
//source: availableTags
//});
 });
   
  var infowindow = null;

  function initialize() { 
   $.ajax({
    url: '../colleagues/allpins',
    error: function (XMLHttpRequest,textStatus,errorThrown) {
      alert("Something went wrong!! Please try again later. Unable to load map");

    },
    success: function(data){

      initializePage(data); 

    },
    type: "get"
  });  

   
 }

  $(document).ready(initialize);
  var address ;
  

  function center()
  {

    name=document.getElementById("name").value;
    
    $.ajax({
      url: '../colleagues/search?search='+name,
      error: function (XMLHttpRequest, textStatus, errorThrown) {
        alert("Something went wrong!! Please try again later.");

      },
      success: function(data){

    
          
if (data=="[]")
{alert("No colleague with this name")}
else
  {

    
  var jsonObj = $.parseJSON(data);
   $.each(jsonObj,function(index,value){
 
    address=value.place;
    image=value.image;

  });
    
  
       
       jQuery("#search_user").html("This Person is based in " +address);
  
       initializeSearch(name,address,image);
        address="";
    image="";
     }},
     type: "get"
   });  
  }
  function initializePage(data) {

    var centerMap = new google.maps.LatLng(0,0);

    var myOptions = {
      zoom: 2,
      center: centerMap,
      minZoom: 2, 
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }

    var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
    var sites = createAllSites(data);
    setMarkers(map, sites);
        /*infowindow = new google.maps.InfoWindow({
                content: "loading..."
              });*/
} 

function createAllSites(data){
  var sites=[];

  var jsonObj = $.parseJSON(data);

  $.each(jsonObj,function(index,value){
    var site=[];
    site.push(value.place);

    
    site.push(parseFloat(value.latitude));
    site.push(parseFloat(value.longitude));

    site.push(2);


    site.push("<div style='text-align:left'><b>Location : <font color=#D75600>"+ value.place+"<br/></font>Total Number of Colleagues : <font color=#D75600>"+value.count+"</font><br/><br/><a data-toggle='modal' href='#example' class='btn' onclick=loadlist('"+value.place+"');>view list</a></div>");

    sites.push(site);
  });
  return sites;
}

function initializeSearch(name,address,image) {


  var centerMap = new google.maps.LatLng(0,0);

  var myOptions = {
    zoom: 4,
    center: centerMap,
    minZoom: 2, 
    mapTypeId: google.maps.MapTypeId.ROADMAP
  }

  var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

  var bikeLayer = new google.maps.BicyclingLayer();
  bikeLayer.setMap(map);

  geocoder = new google.maps.Geocoder();

  geocoder.geocode( { 'address': address}, function(results, status) {
    if (status == google.maps.GeocoderStatus.OK) {
        //In this case it creates a marker, but you can get the lat and lng from the location.LatLng
      
        map.setCenter(results[0].geometry.location);
        var sites = createSites(results[0].geometry,address,name,image);
        setSearchMarkers(map, sites);

        /*infowindow = new google.maps.InfoWindow({
                content: "loading..."
              });*/
}
} );

}

function createSites(geometry,address,name,image){


 var sites = [
 [address, geometry.location.lat(), geometry.location.lng(), 2,"<div style='text-align:center'><font color=#D75600><b>"+name+"</font><br/>Based in : <font color=#D75600>"+address+"</font>"+"<br/><br/><img HEIGHT='150' WIDTH='150' src='"+image+"'>"]
 ];

 return sites;
}

var addressField = document.getElementById('search_address');
var geocoder = new google.maps.Geocoder();





function setMarkers(map, sites) {

  for (var i = 0; i < sites.length; i++) {
    var site = sites[i];
  
    var siteLatLng = new google.maps.LatLng(site[1], site[2]);

    var marker = new google.maps.Marker({
      position: siteLatLng,

      map: map,

      title: site[0],
      zIndex: site[3],
      html: site[4]
    });

    google.maps.event.addListener(marker, "click", function () {

     infowindow = new google.maps.InfoWindow({
      content: "loading..."
    });
     infowindow.setContent(this.html);
     infowindow.open(map, this);

     map.setCenter(this.getPosition());
   });

  }
}
function setSearchMarkers(map, sites) {


  for (var i = 0; i < sites.length; i++) {
    var site = sites[i];
  
    var siteLatLng = new google.maps.LatLng(site[1], site[2]);

    var marker = new google.maps.Marker({
      position: siteLatLng,

      map: map,

      title: site[0],
      zIndex: site[3],
      html: site[4]
    });

    google.maps.event.addListener(marker, "click", function () {

     infowindow = new google.maps.InfoWindow({
      content: "loading..."
    });
     infowindow.setContent(this.html);
     infowindow.open(map, this);

     map.setCenter(this.getPosition());
   });




    infowindow = new google.maps.InfoWindow({
      content: site[4]
    });
    infowindow.open(map, marker);
  } 
    google.maps.event.addListener(infowindow, 'closeclick', function() {  

    initialize(); 
})


}




</script>
</head>

<body>





  <div id="map_canvas" class="map"></div>



</body>
</html>




app/views/colleagues/new.html.erb
<div style="display: inline-block; margin-right:800px">
  <%= link_to image_tag("icon_map.png"), map_colleagues_path , title: 'AppDev Map', rel: 'tooltip' %>
  <%= link_to image_tag("icon_list.png"), colleagues_path , title: 'Colleagues List', rel: 'tooltip' %>
  
</div>


<div class="hr"></div>
</div>
<body>
<center><h2> Add New Colleague </h2></center>

      <%= render 'form' %>


</body>

app/views/colleagues/show.html.erb
<div style="display: inline-block; margin-right:800px">
  <%= link_to image_tag("icon_map.png"), map_colleagues_path , title: 'AppDev Map', rel: 'tooltip' %>
  <%= link_to image_tag("icon_list.png"), colleagues_path , title: 'Colleagues List', rel: 'tooltip' %>
  
</div>




<div class="hr"></div>
</div><p id="notice"><%= notice %></p>

<h2>Colleague Details </h2><br/>

<div style=" min-height: 20px">
</div>
<div style="min-width: 960px; overflow:auto;">
  <table  id="show_table" >
    <thead>
      <tr> 
       <%  if @colleague.attachment.blank? %>
       <td style=" padding-right: 5px; padding-left: 5px; min-width: 50px " align="center">  <%= image_tag ("missing-medium.png") %></td>
       <% else %>
       <td style=" padding-right: 5px; padding-left: 5px" align="center"><%= image_tag @colleague.attachment.url(:medium) %></td>
       <% end %>
     </tr>

     <tr>

      <td style=" padding-right: 5px; padding-left: 5px; padding-bottom: 5px; min-width: 50px"><font size="3"><b>Name </b></font></td> 
      <td style=" padding-right: 5px; padding-left: 5px; min-width: 50px"><%= @colleague.name %></td>
    </tr>

    <tr>
       
      <td style=" padding-right: 5px; padding-left: 5px; padding-bottom: 5px; min-width: 50px"><font size="3"><b>Role </b></font></td> 
      <td style=" padding-right: 5px; padding-left: 5px; min-width: 50px"><%= @colleague.role %></td>
    </tr>


    <tr>
      <td style=" padding-right: 5px; padding-left: 5px;padding-bottom: 5px; min-width: 150px "><font size="3"><b>Office Location </b></font></td>  
      <td style=" padding-right: 5px; padding-left: 5px; min-width: 150px "><%= @colleague.location %></td>
    </tr>


    <tr>
      <td style=" padding-right: 5px; padding-left: 5px; padding-bottom: 5px;min-width: 100px "><font size="3"><b>Project </b></font></td>     
      <td style=" padding-right: 5px; padding-left: 5px; min-width: 150px "><%= @colleague.project %></td>
    </tr>

    <tr>
      <td style=" padding-right: 5px; padding-left: 5px; padding-bottom: 5px;min-width: 100px "><font size="3"><b>Email </b></font></td>     
      <td style=" padding-right: 5px; padding-left: 5px; min-width: 150px "><%= @colleague.email %></td>
    </tr>

    <tr>
      <td style=" padding-right: 5px; padding-left: 5px; padding-bottom: 5px;min-width: 100px "><font size="3"><b>Contact Number </b></font></td>     
      <td style=" padding-right: 5px; padding-left: 5px; min-width: 150px "><%= @colleague.contactnum %></td>
    </tr>


  </thead>

</table>
</div>

<div style=" min-height: 50px">
</div>


<%= link_to 'Back', colleagues_path, :class=> 'btn' %>

<%= link_to 'Edit', edit_colleague_path(@colleague), :class=> 'btn' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
   <title>Worldmap</title>
    <%= stylesheet_link_tag    "application", "colorbox", :media => "all" %>
    <%= javascript_include_tag "application", "jquery.colorbox" %>
    <%= csrf_meta_tags %>


</head>
<body>
<center><div class="wrapper">
<div class="header">


</div>

<div class="content">
  <div class="menubar">

  	 <div class="notice hide" id="devise_notice"><%= notice%></div>
      <div class="alert hide" id="devise_alert"><%=  alert%></div>


  <%= yield %>
</div>



<div class="footer">
  <center>  </center>
</div>

</div>

</center>
</body>


</html>